//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by laser.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LASER_DIALOG                102
#define IDR_MAINFRAME                   128
#define IO                              130
#define IDD_DLG_IO                      130
#define IDI_Green                       131
#define IDI_black                       132
#define IDD_manual                      133
#define IDD_DLG_USER                    134
#define IDD_DLG_PARASET                 135
#define IDI_OK                          141
#define IDI_NG                          142
#define IDB_BITMAP1                     143
#define IDD_DIALOG_MIMA                 144
#define IDC_MSCOMM1                     1000
#define IDC_EDIT1                       1003
#define IDC_EDIT_DQSL                   1003
#define IDC_EDIT_OldMM                  1003
#define IDC_EDIT2                       1004
#define IDC_EDIT_MJBM                   1004
#define IDC_EDIT_PartNum                1004
#define IDC_EDIT_NewMM                  1004
#define IDC_EDIT3                       1005
#define IDC_EDIT_XTLS                   1005
#define IDC_EDIT_CustomNo               1005
#define IDC_EDIT_TwoNMM                 1005
#define IDC_EDIT4                       1006
#define IDC_EDIT_BZSL                   1006
#define IDC_EDIT_PlantNo                1006
#define IDC_COMBO1                      1007
#define IDC_COMBO_SCBC                  1007
#define IDC_COMBO_PARA                  1007
#define IDC_COMBO2                      1008
#define IDC_COMBO_PRO                   1008
#define IDC_COMBO_NolePokeyoka          1008
#define IDC_EDIT5                       1009
#define IDC_EDIT_ZSHM                   1009
#define IDC_EDIT_Certificate            1009
#define IDC_EDIT6                       1010
#define IDC_EDIT_LSHM                   1010
#define IDC_EDIT_Brand                  1010
#define IDC_EDIT7                       1011
#define IDC_EDIT_EWHM                   1011
#define IDC_EDIT_FixNo                  1011
#define IDC_EDIT8                       1012
#define IDC_EDIT_CPZJ                   1012
#define IDC_EDIT_AUTOLIVNO              1012
#define IDC_EDIT9                       1013
#define IDC_EDIT_AUTOLIV                1013
#define IDC_EDIT_COMPONENTNO            1013
#define IDC_EDIT10                      1014
#define IDC_EDIT_KHBH                   1014
#define IDC_EDIT_CARTYPE                1014
#define IDC_EDIT_GYSBM                  1014
#define IDC_EDIT11                      1015
#define IDC_EDIT_RZLX                   1015
#define IDC_EDIT_LOGONO                 1015
#define IDC_EDIT12                      1016
#define IDC_EDIT_CXH                    1016
#define IDC_EDIT_NHACODE                1016
#define IDC_EDIT_DATA                   1016
#define IDC_EDIT13                      1017
#define IDC_EDIT_LOGO                   1017
#define IDC_EDIT_VISFILE                1017
#define IDC_EDIT14                      1018
#define IDC_EDIT_PINP                   1018
#define IDC_EDIT_BANBEN                 1018
#define IDC_EDIT_CPZJ2                  1018
#define IDC_EDIT15                      1019
#define IDC_EDIT_FCK                    1019
#define IDC_EDIT_AUTOLIV2               1019
#define IDC_EDIT16                      1020
#define IDC_EDIT_GCBH                   1020
#define IDC_EDIT_MOJU                   1020
#define IDC_EDIT_GYSBM2                 1020
#define IDC_EDIT17                      1021
#define IDC_EDIT_NHA                    1021
#define IDC_EDIT_DATA2                  1021
#define IDC_EDIT18                      1022
#define IDC_EDIT_ZJBH                   1022
#define IDC_EDIT_MOJU2                  1022
#define IDC_EDIT19                      1023
#define IDC_EDIT_TEMP                   1023
#define IDC_BUTTON7                     1024
#define IDC_BTN_YAJIN                   1024
#define IDC_BTN_GUANBI                  1024
#define IDC_BUTTON8                     1025
#define IDC_BTN_TAIQI                   1025
#define IDC_BTN_ADDPro                  1025
#define IDC_BUTTON9                     1026
#define IDC_BTN_HOULA                   1026
#define IDC_BTN_SETMR                   1026
#define IDC_BUTTON10                    1027
#define IDC_BTN_QIANJIN                 1027
#define IDC_BUTTON11                    1028
#define IDC_BTN_SHANGSHENG              1028
#define IDC_BUTTON12                    1029
#define IDC_BTN_XIAJIANG                1029
#define IDC_BUTTON13                    1030
#define IDC_BTN_SSTC                    1030
#define IDC_BUTTON14                    1031
#define IDC_BTN_SSHT                    1031
#define IDC_BUTTON15                    1032
#define IDC_BTN_JLTC                    1032
#define IDC_BUTTON16                    1033
#define IDC_BTN_JLHT                    1033
#define IDC_BUTTON17                    1034
#define IDC_BTN_VISKZ                   1034
#define IDC_BUTTON18                    1035
#define IDC_BTN_VISM                    1035
#define IDC_BUTTON19                    1036
#define IDC_BTN_READ                    1036
#define IDC_EDIT_INFO                   1037
#define IDC_EDIT_ZSHM2                  1037
#define IDC_BTN_DAOCHU                  1038
#define IDC_BTN_PARA                    1039
#define IDC_BTN_PRO                     1040
#define IDC_BTN_JILU                    1041
#define IDC_BTN_INIT                    1042
#define IDC_BTN_STOP                    1043
#define IDC_BTN_QUIT                    1044
#define IDC_BTN_USER                    1045
#define IDC_EDIT_MOJERRO                1046
#define IDC_BTN_YES                     1047
#define IDC_BTN_IO                      1048
#define IDC_BTN_MANUAL                  1049
#define IDC_LIST2                       1051
#define IDC_LIST_IO                     1051
#define IDC_CHECK1                      1054
#define IDC_RADIO1                      1057
#define IDC_RADIO2                      1058
#define IDC_LIST1                       1059
#define IDC_LIST_ParaBB                 1059
#define IDC_COMBO_ID                    1060
#define IDC_YES                         1061
#define IDC_CANCEL                      1062
#define IDC_EDIT_KEYWORD                1063
#define IDC_DATETIMEPICKER2             1067
#define IDC_DATETIMEPICKER3             1068
#define IDC_BTN_DEL                     1071
#define IDC_EDIT_Erro1                  1073
#define IDC_BTN_XIUGAI                  1074
#define IDC_STATIC_Icon                 1077
#define IDC_BUTTON1                     1079
#define IDC_BTN_KaiGuan                 1079
#define IDC_BUTTON2                     1080
#define IDC_BTN_DABIAO                  1080
#define IDC_BTN_CANCELL                 1080
#define IDC_BUTTON3                     1081
#define IDC_BTN_DAYIN                   1081
#define IDC_MSCOMM2                     1082
#define IDC_MSCOMM3                     1083
#define IDC_EDIT20                      1084
#define IDC_STATIC_NG                   1085
#define IDC_COMBO_SSKaiG                1086
#define IDC_COMBO_SSGuangQ              1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
